

services:
  scraper:
    build: .
    volumes:
      - ./downloads:/app/downloads
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=bhargavagonugunta123@gmail.com
      - SMTP_PASS=mget cbyi gvzp ifam
      - SMTP_FROM=bhargavagonugunta123@gmail.com
      - SMTP_TO=kpdasari@gmail.com
    working_dir: /app
